pull_request_rules:
  - name: Test passed
    conditions:
      - or:
        - base=main
      - "status-success=Run Python Tests (3.7)"
      - "status-success=Run Python Tests (3.11)"
    actions:
